medicine/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #/medicine/
    url(r'^$',views.homePage, name='homePage'),
    url(r'^product/$',views.product, name='product'),
    url(r'^contact/$',views.contact, name='contact'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('medicine.urls', namespace='medicine')),
]

medicine/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    medicineName = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    ablum_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.medicineName

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    Song_title = models.CharField(max_length=250)

medicine/views.py
from django.http import Http404
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from .models import Album


# def product(request):
#     all_albums =Album.objects.all()
#     #template = loader.get_template('medicine/product.html')
#     # context = {
#     #     'all_albums' : all_albums,
#     # }
#     return render (request,'medicine/product.html')
    #return render (request,'medicine/index.html', {'album' : all_albums })

def detail(request, album_id):
    try:
        album = Album.objects.get(pk=album_id)
    except Album.DoesNotExist:
        raise Http404("album not exist")
    return render (request,'medicine/detail.html', {'album' : album })
    #return HttpResponse("<h2>Details for Album id: "+str(album_id)+"</h2>")

def homePage(request):
    return render (request, 'medicine/homePage.html')

def product(request):
    return render (request, 'medicine/product.html')

def contact(request):
    return render (request, 'medicine/contact.html')

website/views.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

medicine/templates/medicine/contact.html
<!-- Load static file-->
{% load staticfiles %}
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'medicine/style.css' %}" />
<nav class="navbar navbar-defalut " >
  <div class="container - fluid">
    <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'medicine:homePage' %}" >HomePage</a>
          <a class="navbar-brand" href="{% url 'medicine:contact' %}" >Contact</a>
          <a class="navbar-brand" href="{% url 'medicine:product' %}" >Product</a>
    </div>
  </div>
</nav>
<!-- End load-->
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
<!--Google Map-->
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
 <!--Google Map-->
</head>

<body>
<title>Contact</title>
<div class="container">
<div class="mx-auto"><img src="http://womenofrubies.com/wp-content/uploads/2017/11/Listening01.jpg" style="width: 100%;height: 300px"></div>

<div class="row">
  <div class="col">
  	<div class="form-group">
			  <label for="name">Name:</label>
			  <input type="text" class="form-control" id="name" placeholder="Please enter your name here.">
	</div>
	<div class="form-group">
			  <label for="password">Password:</label>
			  <input type="email" class="form-control" id="email" placeholder="Please enter your email here.">
	</div>
	<div class="form-group">
			  <label for="comment">Comment:</label>
			  <textarea class="form-control" rows="5" id="comment" placeholder="Please enter your comment here."></textarea>
	</div>
</div>

</div>

</div>
</body>

medicine/templates/medicine/detail.html
{{ album}}

medicine/templates/medicine/homePage.html
<!-- Load static file-->
{% load staticfiles %}
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'medicine/style.css' %}" />
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <img src="https://www.tenstickers.co.uk/wall-stickers/img/preview/luigi-videogame-wall-sticker-3653.png" style="height: 20px;width: 20px">


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">HomePage<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://hk.yahoo.com/">Product</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://hk.yahoo.com/">Profile</a>
      </li>
    </ul>

  </div>
</nav>
<!-- End load-->


<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</head>

<body>
<title>HomePage</title>
<div class="container">
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="http://medicalcouncil.kerala.gov.in/wp-content/uploads/2018/01/modern-medicine1-2.jpg" alt="First slide" style="height: 60%">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://www.biospectrumindia.com/uploads/articles/tech_in_healthcare-9509.jpg" alt="Second slide" style="height: 60%">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://image.flaticon.com/sprites/share/packs/119040-medical-elements.png" alt="Third slide" style="height: 60%">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="container">
	<h2>About Us</h2>
	<p>Too often, we treat heaven like a house we bought but didn't move in to, or a trip we planned but didn't take. We seldom think about it or make any attempt to find out more about our eternal home. We busy ourselves with making more plans for this life rather than investing in eternity.

	In the Word of God, from Genesis to Revelation, the word heaven is used to describe three different realms: the atmospheric realm, the realm of the galaxies, and the heavenly country where God resides. God is in control of all three realms—it is through His power that He is sustaining all three. And still, as incredible, vast, and transcendent as He is, God lives in the believer's heart.</p>
	<h2>Company History</h2>

	<p>Pater noster, qui es in caelis:
	sanctificetur nomen tuum;
	adveniat regnum tuum;
	fiat voluntas tua, sicut in caelo, et in terra.
	Panem nostrum cotidianum da nobis hodie;
	et dimitte nobis debita nostra,
	sicut et nos dimittimus debitoribus nostris;
	et ne nos inducas in tentationem;
	sed libera nos a malo.Our Father is very much in heaven, and yet He walks with us and talks with us every single moment of every day. God is almighty—He is the sovereign Creator—and yet He also comforts us, blesses us, and speaks a word of peace to our troubled hearts. Our Father is holding together the engine that orchestrates the vast galaxies as they rotate, and He keeps them from spinning out of control. Yet, He is closer to us than our hands and feet.</p>
</div></div>
</body>
<style>
h2 { color: #ff9900; font-family: 'Rouge Script', cursive; font-size: 30px; font-weight: normal; line-height: 48px; margin: 0 0 00px; text-align: center; text-shadow: 1px 1px 2px #082b34; }


h1 { color: #a7e8f8; font-family: 'Julius Sans One', sans-serif; font-size: 22px; font-weight: bold; line-height: 32px; margin: 0 0 24px; text-shadow: 1px 1px 1px #082b34; }


p { color: #e580ff; font-family: 'Carme', sans-serif; font-size: 16px; line-height: 24px; margin: 0 0 24px; }


a { color: #CEF0D4; text-decoration: underline; }


a:hover { color: #a7e8f8; text-decoration: underline; }



</style>
<section id="footer">
    <div class="container">
      <div class="text-center text-xs-center text-sm-left text-md-left">
        <div class="col-xs-12 col-sm-4 col-md-4">
          <h5>Quick links</h5>
          <ul class="list-unstyled quick-links">
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>HomePage</a></li>
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Contact</a></li>
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Product</a></li>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
          <p>Designed by <u><a href="#">MyLam and Felix</a></u></p>
          <p class="h6">&copy All right Reversed.</p>
        </div>
        </hr>
      </div>
    </div>
  </section>
  <!-- ./Footer -->
  <style>
    / Footer /
@import url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css');
section {
    padding: 10px 0;
}

section .section-title {
    text-align: center;
    color: #007b5e;
    margin-bottom: 50px;
    text-transform: uppercase;
}
#footer {
    background: #007b5e !important;
}
#footer h5{
  padding-left: 10px;
    border-left: 3px solid #eeeeee;
    padding-bottom: 6px;
    margin-bottom: 20px;
    color:#ffffff;
}
#footer a {
    color: #ffffff;
    text-decoration: none !important;
    background-color: transparent;
    -webkit-text-decoration-skip: objects;
}
#footer ul.social li{
  padding: 3px 0;
}
#footer ul.social li a i {
    margin-right: 5px;
  font-size:25px;
  -webkit-transition: .5s all ease;
  -moz-transition: .5s all ease;
  transition: .5s all ease;
}
#footer ul.social li:hover a i {
  font-size:30px;
  margin-top:-10px;
}
#footer ul.social li a,
#footer ul.quick-links li a{
  color:#ffffff;
}
#footer ul.social li a:hover{
  color:#eeeeee;
}
#footer ul.quick-links li{
  padding: 3px 0;
  -webkit-transition: .5s all ease;
  -moz-transition: .5s all ease;
  transition: .5s all ease;
}
#footer ul.quick-links li:hover{
  padding: 3px 0;
  margin-left:5px;
  font-weight:700;
}
#footer ul.quick-links li a i{
  margin-right: 5px;
}
#footer ul.quick-links li:hover a i {
    font-weight: 700;
}

@media (max-width:767px){
  #footer h5 {
    padding-left: 0;
    border-left: transparent;
    padding-bottom: 0px;
    margin-bottom: 10px;
}
}

  </style>

medicine/templates/medicine/index.html
<!DOCTYPE onloadedmetadata="html">
<html lang="en">
<head>
<meta charset="UTF-8">
</head>

<body>
  {% if all_albums %}
  <h3>Albums</h3>
  <title>medicine</title>
    <ul>
      {% for album in all_albums %}
          <li><a href="/medicine/{{ album.id }}/">  {{album.album_title}} </a></li>


      {% endfor %}
    </ul>
    {% else %}
      <h3>No Album</h3>
    {% endif %}
</body>
</html>

medicine/templates/medicine/product.html

<!-- Load static file-->
{% load staticfiles %}
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'medicine/style.css' %}" />
<nav class="navbar navbar-defalut " >
  <div class="container - fluid">
    <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'medicine:homePage' %}" >HomePage</a>
          <a class="navbar-brand" href="{% url 'medicine:contact' %}" >Contact</a>
          <a class="navbar-brand" href="{% url 'medicine:product' %}" >Product</a>
    </div>
  </div>
</nav>
<!-- End load-->
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>

<body>
<title>Product</title>
<div class="container">
  <h2>Product</h2>
  Please click on the tab
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#Heart">Heart</a></li>
    <li><a data-toggle="tab" href="#Brain">Brain</a></li>
    <li><a data-toggle="tab" href="#Bone">Bone</a></li>
  </ul>

  <div class="tab-content">
    <div id="Heart" class="tab-pane fade in active">
      <h3>Heart</h3>
      <!--1 medicine 1-->
      <div class="container py-3">
    <div class="card">
      <div class="row ">
        <div class="col-md-4">
            <img src="http://cimg2.163.com/tech/book/pszhongwenchuangyi/ch01.files/image001.jpg" class="w-100">
          </div>
          <div class="col-md-8 px-3">
            <div class="card-block px-3">
              <h4 class="card-title">Heart 1</h4>
              <p class="card-text">1:1  [kjv]   In the beginning God created the heaven and the earth.
    [bbe]   At the first God made the heaven and the earth.</p>
              <a href="#" class="btn btn-primary">Read More</a>
            </div>
          </div>

        </div>
      </div>
    </div>
   <!--medicine 1 end-->
   <!--1 medicine 2-->
      <div class="container py-3">
    <div class="card">
      <div class="row ">
        <div class="col-md-4">
            <img src="https://upload.wikimedia.org/wikipedia/commons/4/44/Coraz%C3%B3n.svg" class="w-100">
          </div>
          <div class="col-md-8 px-3">
            <div class="card-block px-3">
              <h4 class="card-title">Heart 2</h4>
              <p class="card-text">1:2  [kjv]   And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.</p>
              <a href="#" class="btn btn-primary">Read More</a>
            </div>
          </div>

        </div>
      </div>
    </div>
   <!--medicine 2 end-->
   <!--1 medicine 3-->
      <div class="container py-3">
    <div class="card">
      <div class="row ">
        <div class="col-md-4">
            <img src="https://pic.baike.soso.com/ugc/baikepic2/13465/20180116170807-1886404634_jpg_935_941_41422.jpg/0" class="w-100">
          </div>
          <div class="col-md-8 px-3">
            <div class="card-block px-3">
              <h4 class="card-title">Heart 3</h4>
              <p class="card-text">And the earth was waste and without form; and it was dark on the face of the deep: and the Spirit of God was moving on the face of the waters.</p>
              <a href="#" class="btn btn-primary">Read More</a>
            </div>
          </div>

        </div>
      </div>
    </div>
   <!--medicine 3 end-->
    </div>
    <div id="Brain" class="tab-pane fade">
      <h3>Brain</h3>
            <!--2 medicine 1-->
      <div class="container py-3">
    <div class="card">
      <div class="row ">
        <div class="col-md-4">
            <img src="https://st2.depositphotos.com/3682225/7467/v/950/depositphotos_74679019-stock-illustration-head-brain-icon-think-design.jpg" class="w-100">
          </div>
          <div class="col-md-8 px-3">
            <div class="card-block px-3">
              <h4 class="card-title">Brain 1</h4>
              <p class="card-text">1:3  [kjv]   And God said, Let there be light: and there was light.
    [bbe]   And God said, Let there be light: and there was light.</p>
              <a href="#" class="btn btn-primary">Read More</a>
            </div>
          </div>

        </div>
      </div>
    </div>
   <!--medicine 1 end-->
   <!--2 medicine 2-->
      <div class="container py-3">
    <div class="card">
      <div class="row ">
        <div class="col-md-4">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbT7T4f6fxTtzDeEVVOcRGZTpn7HBb2gL7aqBrCGPOO6dYs3VB-Q" class="w-100">
          </div>
          <div class="col-md-8 px-3">
            <div class="card-block px-3">
              <h4 class="card-title">Brain 2</h4>
              <p class="card-text">1:4  [kjv]   And God saw the light, that it was good: and God divided the light from the darkness.</p>
              <a href="#" class="btn btn-primary">Read More</a>
            </div>
          </div>

        </div>
      </div>
    </div>
   <!--medicine 2 end-->
   <!--2 medicine 3-->
      <div class="container py-3">
    <div class="card">
      <div class="row ">
        <div class="col-md-4">
            <img src="http://img0.pconline.com.cn/pconline/1211/26/3083925_ibm_human_brain.jpg" class="w-100">
          </div>
          <div class="col-md-8 px-3">
            <div class="card-block px-3">
              <h4 class="card-title">Brain 3</h4>
              <p class="card-text"> [bbe]   And God, looking on the light, saw that it was good: and God made a division between the light and the dark,</p>
              <a href="#" class="btn btn-primary">Read More</a>
            </div>
          </div>

        </div>
      </div>
    </div>
   <!--medicine 3 end-->
    </div>


        <div id="Bone" class="tab-pane fade">
      <h3>Bone</h3>
      <!--3 medicine 1-->
      <div class="container py-3">
    <div class="card">
      <div class="row ">
        <div class="col-md-4">
            <img src="http://www.interactive-biology.com/wp-content/uploads/2012/06/MaleSkeletonsitting1-1280x640.jpg" class="w-100">
          </div>
          <div class="col-md-8 px-3">
            <div class="card-block px-3">
              <h4 class="card-title">Lorem ipsum dolor sit amet</h4>
              <p class="card-text">And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.</p>
              <a href="#" class="btn btn-primary">Read More</a>
            </div>
          </div>

        </div>
      </div>
    </div>
   <!--medicine 1 end-->
   <!--3 medicine 2-->
      <div class="container py-3">
    <div class="card">
      <div class="row ">
        <div class="col-md-4">
            <img src="https://www.sportsdietitians.com.au/wp-content/uploads/2015/05/Bone-health1.jpg" class="w-100">
          </div>
          <div class="col-md-8 px-3">
            <div class="card-block px-3">
              <h4 class="card-title">Lorem ipsum dolor sit amet</h4>
              <p class="card-text">Naming the light, Day, and the dark, Night. And there was evening and there was morning, the first day.</p>
              <a href="#" class="btn btn-primary">Read More</a>
            </div>
          </div>

        </div>
      </div>
    </div>
   <!--medicine 2 end-->
   <!--3 medicine 3-->
      <div class="container py-3">
    <div class="card">
      <div class="row ">
        <div class="col-md-4">
            <img src="https://cdn.pixabay.com/photo/2013/07/13/10/27/bone-157272_1280.png" class="w-100">
          </div>
          <div class="col-md-8 px-3">
            <div class="card-block px-3">
              <h4 class="card-title">Lorem ipsum dolor sit amet</h4>
              <p class="card-text">1:6  [kjv]   And God said, Let there be a firmament in the midst of the waters, and let it divide the waters from the waters.</p>
              <a href="#" class="btn btn-primary">Read More</a>
            </div>
          </div>

        </div>
      </div>
    </div>
   <!--medicine 3 end-->
    </div>

</div>

</body>